"""Build a rigged, animated exercise figure and export GLB + thumbnail.

Runs headless inside Blender in CI (no GPU needed):

    blender -b -noaudio --python-exit-code 1 -P pipeline/build_exercise.py -- exercises/squat.json site/assets

v0.4: the figure is a real anatomical human generated by MPFB2 (MakeHuman
for Blender) — male, muscle 0.9 — rigged with the canonical MakeHuman
skeleton. Poses stay in the same exercise JSONs: a hidden synthetic
"driver" rig evaluates them, then each MakeHuman bone is aimed at the
driver bone's world direction (shortest arc), so the retarget is
independent of the two rigs' different rest poses (MPFB rests in A-pose).
Active muscle regions are painted onto the body via MakeHuman's own
skin-weight territories. Writes <id>.glb and <id>.png (mid-rep frame).
"""

import importlib
import json
import math
import os
import sys
import urllib.request
import zipfile

import bmesh
import bpy
from mathutils import Matrix, Quaternion, Vector

MPFB_URL = ("https://extensions.blender.org/download/"
            "sha256:b5cdc8b08147e0c6463e4faa01147491b13a0b062f73415363f029debd11c934/"
            "add-on-mpfb-v2.0.16.zip?repository=%2Fapi%2Fv1%2Fextensions%2F"
            "&blender_version_min=4.2.0")

# Driver skeleton (pose JSONs are authored against these rest directions).
# World coords, character faces -Y. name: (head, tail)
BONES = {
    "pelvis":      ((0.00, 0.0, 0.95), (0.00, 0.0, 1.06)),
    "spine":       ((0.00, 0.0, 1.06), (0.00, 0.0, 1.30)),
    "chest":       ((0.00, 0.0, 1.30), (0.00, 0.0, 1.50)),
    "neck":        ((0.00, 0.0, 1.50), (0.00, 0.0, 1.58)),
    "head":        ((0.00, 0.0, 1.58), (0.00, 0.0, 1.76)),
    "upper_arm.L": ((0.18, 0.0, 1.46), (0.42, 0.0, 1.46)),
    "forearm.L":   ((0.42, 0.0, 1.46), (0.66, 0.0, 1.46)),
    "hand.L":      ((0.66, 0.0, 1.46), (0.78, 0.0, 1.46)),
    "thigh.L":     ((0.10, 0.0, 0.95), (0.10, 0.0, 0.52)),
    "shin.L":      ((0.10, 0.0, 0.52), (0.10, 0.0, 0.09)),
    "foot.L":      ((0.10, 0.0, 0.09), (0.10, -0.18, 0.02)),
}

PARENTS = {
    "spine": "pelvis", "chest": "spine", "neck": "chest", "head": "neck",
    "upper_arm.L": "chest", "forearm.L": "upper_arm.L", "hand.L": "forearm.L",
    "thigh.L": "pelvis", "shin.L": "thigh.L", "foot.L": "shin.L",
}

# driver bone -> MakeHuman default-rig bone (aim transfer, parent-first order)
RETARGET = [
    ("pelvis", "root"),
    ("spine", "spine03"), ("chest", "spine01"),
    ("neck", "neck01"), ("head", "head"),
    ("thigh.L", "upperleg01.L"), ("thigh.L", "upperleg02.L"),
    ("shin.L", "lowerleg01.L"), ("shin.L", "lowerleg02.L"), ("foot.L", "foot.L"),
    ("thigh.R", "upperleg01.R"), ("thigh.R", "upperleg02.R"),
    ("shin.R", "lowerleg01.R"), ("shin.R", "lowerleg02.R"), ("foot.R", "foot.R"),
    ("upper_arm.L", "upperarm01.L"), ("upper_arm.L", "upperarm02.L"),
    ("forearm.L", "lowerarm01.L"), ("forearm.L", "lowerarm02.L"), ("hand.L", "wrist.L"),
    ("upper_arm.R", "upperarm01.R"), ("upper_arm.R", "upperarm02.R"),
    ("forearm.R", "lowerarm01.R"), ("forearm.R", "lowerarm02.R"), ("hand.R", "wrist.R"),
]

# exercise-metadata muscle name -> (bone territories, side, rest z-range).
#
# Three filters, because no two of them suffice. Bone: MakeHuman splits each
# limb into a short proximal segment and a long belly (upperarm01 = deltoid
# cap, upperarm02 = biceps/triceps belly; upperleg02 = quad/ham belly;
# lowerleg01 = calf). Side ("front"/"back", character faces -Y): separates
# antagonists sharing a bone. Height: the torso census settles it — spine02
# owns 306 skin verts and just 2 of them are posterior, so pecs and abs both
# live on spine02's anterior skin and only a rest-pose z cut can part them
# (spine01 = 324 verts / 227 posterior = upper back, i.e. the lats' anchor).
# Ranges are rest-pose metres: pelvis ~0.95, navel ~1.15, sternum ~1.30,
# clavicle ~1.45, chin ~1.55.
MUSCLE_SPEC = {
    "quads": (("upperleg02",), "front", None),
    "hamstrings": (("upperleg02",), "back", None),
    "glutes": (("pelvis", "upperleg01"), "back", (0.82, 1.00)),
    "calves": (("lowerleg01",), "back", None),
    "core": (("spine02", "spine03", "spine04"), "front", (0.98, 1.24)),
    "abs": (("spine02", "spine03", "spine04"), "front", (0.98, 1.24)),
    "lower back": (("spine03", "spine04", "spine05"), "back", (0.92, 1.14)),
    "chest": (("spine01", "spine02", "breast"), "front", (1.24, 1.46)),
    "pecs": (("spine01", "spine02", "breast"), "front", (1.24, 1.46)),
    "lats": (("spine01", "spine02", "spine03"), "back", (1.08, 1.42)),
    "back": (("spine01", "spine02", "spine03"), "back", (1.08, 1.42)),
    "traps": (("neck01", "neck02", "neck03", "clavicle", "spine01"), "back",
              (1.36, 1.56)),
    "shoulders": (("shoulder01", "upperarm01"), None, None),
    "front delts": (("shoulder01", "upperarm01"), "front", None),
    "delts": (("shoulder01", "upperarm01"), None, None),
    "biceps": (("upperarm02",), "front", None),
    "triceps": (("upperarm02",), "back", None),
    "forearms": (("lowerarm01", "lowerarm02"), None, None),
}

HELPER_GROUPS = ("HelperGeometry", "JointCubes", "eye.L", "eye.R")

SKIN_COLOR = (0.62, 0.64, 0.68, 1.0)
PRIMARY_COLOR = (0.62, 0.02, 0.03, 1.0)
SECONDARY_COLOR = (0.80, 0.26, 0.02, 1.0)


# ---------------------------------------------------------------- mpfb setup

def ensure_mpfb():
    version = f"{bpy.app.version[0]}.{bpy.app.version[1]}"
    ext_root = os.path.expanduser(f"~/.config/blender/{version}/extensions/user_default")
    dest = os.path.join(ext_root, "mpfb")
    if not os.path.isdir(dest):
        os.makedirs(ext_root, exist_ok=True)
        zpath = "/tmp/mpfb.zip"
        if not os.path.exists(zpath):
            req = urllib.request.Request(       # site 403s python's default UA
                MPFB_URL, headers={"User-Agent": "Mozilla/5.0 (X11; Linux x86_64)"})
            with urllib.request.urlopen(req) as resp, open(zpath, "wb") as f:
                f.write(resp.read())
        with zipfile.ZipFile(zpath) as z:
            names = z.namelist()
            if any(n.split("/")[0] == "blender_manifest.toml" for n in names):
                z.extractall(dest)
            else:
                z.extractall(ext_root)
                top = names[0].split("/")[0]
                if top != "mpfb":
                    os.rename(os.path.join(ext_root, top), dest)
    bpy.ops.preferences.addon_enable(module="bl_ext.user_default.mpfb")


def dynamic_import(absolute_package_str, key):
    """MPFB's own quirk: extensions land at unknown module paths."""
    for amod in list(sys.modules):
        if amod.endswith(absolute_package_str):
            return getattr(importlib.import_module(amod), key)
    raise ValueError(f"no module ending in {absolute_package_str}")


def create_human():
    HumanService = dynamic_import("mpfb.services.humanservice", "HumanService")
    HumanObjectProperties = dynamic_import("mpfb.entities.objectproperties",
                                           "HumanObjectProperties")
    TargetService = dynamic_import("mpfb.services.targetservice", "TargetService")
    basemesh = HumanService.create_human()
    for prop, value in (("gender", 1.0), ("muscle", 1.0), ("weight", 0.55)):
        HumanObjectProperties.set_value(prop, value, entity_reference=basemesh)
    TargetService.reapply_macro_details(basemesh)
    rig = HumanService.add_builtin_rig(basemesh, "default")
    return basemesh, rig


def strip_helpers(basemesh):
    """MakeHuman's base mesh ships clothes-fitting scaffolding — remove it."""
    kill = {g.index for g in basemesh.vertex_groups if g.name in HELPER_GROUPS}
    doomed = [v.index for v in basemesh.data.vertices
              if any(ge.group in kill for ge in v.groups)]
    bm = bmesh.new()
    bm.from_mesh(basemesh.data)
    bm.verts.ensure_lookup_table()
    bmesh.ops.delete(bm, geom=[bm.verts[i] for i in doomed], context="VERTS")
    bm.to_mesh(basemesh.data)
    bm.free()


# ------------------------------------------------------------------ painting

def make_material(name, color, emission=0.0, roughness=0.55, subsurface=0.0):
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes["Principled BSDF"]
    bsdf.inputs["Base Color"].default_value = color
    bsdf.inputs["Roughness"].default_value = roughness
    if emission:
        bsdf.inputs["Emission Color"].default_value = color
        bsdf.inputs["Emission Strength"].default_value = emission
    if subsurface and "Subsurface Weight" in bsdf.inputs:
        bsdf.inputs["Subsurface Weight"].default_value = subsurface
    return mat


def highlight_sets(spec):
    """Exercise metadata -> lists of muscle keys we know how to paint."""
    def keys(names):
        return [m.lower() for m in names if m.lower() in MUSCLE_SPEC]
    primary = keys(spec.get("primary", []))
    secondary = [m for m in keys(spec.get("secondary", [])) if m not in primary]
    return primary, secondary


def paint_muscles(basemesh, rig, materials, primary, secondary):
    """Paint faces whose dominant skin-weight territory belongs to an active
    muscle, split front/back so antagonists don't bleed into each other.
    Only real rig-bone groups count — MakeHuman's meta groups (body/Left/
    Right/Mid) carry full weights everywhere and must be ignored. The
    membership field is Laplacian-smoothed so borders curve."""
    mesh = basemesh.data
    name_by_index = {g.index: g.name for g in basemesh.vertex_groups}
    bones = {b.name: b for b in rig.data.bones}
    axis_y = {name: (b.head_local.y + b.tail_local.y) / 2 for name, b in bones.items()}

    def matches(muscle_key, bone_name, vert):
        territories, side, z_range = MUSCLE_SPEC[muscle_key]
        if bone_name.split(".")[0] not in territories:
            return False
        if z_range is not None and not (z_range[0] <= vert.co.z <= z_range[1]):
            return False
        if side is None:
            return True
        # character faces -Y: anterior muscles sit in front of the bone axis
        mid = axis_y.get(bone_name, 0.0)
        return vert.co.y < mid if side == "front" else vert.co.y > mid

    score_p, score_s = [], []
    census = {}
    for v in mesh.vertices:
        best, best_w = None, 0.0
        for ge in v.groups:
            name = name_by_index.get(ge.group)
            if name in bones and ge.weight > best_w:
                best, best_w = name, ge.weight
        if best:
            slot = census.setdefault(best.split(".")[0], [0, 0])
            slot[0] += 1
            slot[1] += 1 if v.co.y > axis_y.get(best, 0.0) else 0
        score_p.append(1.0 if best and any(matches(m, best, v) for m in primary) else 0.0)
        score_s.append(1.0 if best and any(matches(m, best, v) for m in secondary) else 0.0)

    # which bones actually own skin (and how much of it is posterior) — the
    # muscle map is only as good as this census, so it goes in the CI log
    top = sorted(census.items(), key=lambda kv: -kv[1][0])[:14]
    print("CENSUS " + " ".join(f"{n}:{c[0]}/{c[1]}b" for n, c in top))
    print(f"CENSUS painted primary={sum(score_p):.0f} secondary={sum(score_s):.0f}")

    neighbors = [[] for _ in mesh.vertices]
    for edge in mesh.edges:
        a, b = edge.vertices
        neighbors[a].append(b)
        neighbors[b].append(a)
    for _ in range(4):
        for score in (score_p, score_s):
            snapshot = score[:]
            for i, ns in enumerate(neighbors):
                if ns:
                    score[i] = 0.5 * snapshot[i] + \
                        0.5 * sum(snapshot[j] for j in ns) / len(ns)

    mesh.materials.clear()
    mesh.materials.append(materials["skin"])
    mesh.materials.append(materials["primary"])
    mesh.materials.append(materials["secondary"])
    for poly in mesh.polygons:
        p = sum(score_p[i] for i in poly.vertices) / len(poly.vertices)
        s = sum(score_s[i] for i in poly.vertices) / len(poly.vertices)
        if p > 0.45 and p >= s:
            poly.material_index = 1
        elif s > 0.45:
            poly.material_index = 2
        else:
            poly.material_index = 0


# ---------------------------------------------------------------- retargeting

def mirror_name(name):
    return name[:-2] + ".R" if name.endswith(".L") else name


def full_skeleton():
    bones, parents = {}, {}
    for name, (head, tail) in BONES.items():
        bones[name] = (Vector(head), Vector(tail))
        if name.endswith(".L"):
            r = mirror_name(name)
            bones[r] = (Vector((-head[0], head[1], head[2])),
                        Vector((-tail[0], tail[1], tail[2])))
    for child, parent in PARENTS.items():
        parents[child] = parent
        if child.endswith(".L"):
            parents[mirror_name(child)] = mirror_name(parent)
    return bones, parents


def build_driver(bones, parents):
    arm_data = bpy.data.armatures.new("Driver")
    arm_obj = bpy.data.objects.new("Driver", arm_data)
    bpy.context.scene.collection.objects.link(arm_obj)
    bpy.context.view_layer.objects.active = arm_obj
    bpy.ops.object.mode_set(mode="EDIT")
    for name, (head, tail) in bones.items():
        eb = arm_data.edit_bones.new(name)
        eb.head, eb.tail, eb.roll = head, tail, 0.0
    for child, parent in parents.items():
        arm_data.edit_bones[child].parent = arm_data.edit_bones[parent]
    bpy.ops.object.mode_set(mode="OBJECT")
    return arm_obj


def pose_targets(kf_bones):
    """Expand 'thigh.*' wildcards into mirrored .L/.R transforms."""
    for name, xf in kf_bones.items():
        rot = xf.get("rot", [0, 0, 0])
        loc = xf.get("loc")
        if name.endswith(".*"):
            base = name[:-2]
            yield base + ".L", rot, loc
            mrot = [rot[0], -rot[1], -rot[2]]
            mloc = [-loc[0], loc[1], loc[2]] if loc else None
            yield base + ".R", mrot, mloc
        else:
            yield name, rot, loc


def pose_driver(driver, kf):
    root_offset = Vector((0, 0, 0))
    for bone_name, rot, loc in pose_targets(kf.get("bones", {})):
        pb = driver.pose.bones[bone_name]
        pb.rotation_mode = "XYZ"
        pb.rotation_euler = [math.radians(a) for a in rot]
        if loc is not None and bone_name == "pelvis":
            root_offset = Vector(loc)
    bpy.context.view_layer.update()
    return root_offset


def driver_target_dir(syn_pb):
    """World direction the driver bone points in its current pose."""
    syn_rest_dir = (Vector(syn_pb.bone.tail_local) -
                    Vector(syn_pb.bone.head_local)).normalized()
    delta = (syn_pb.matrix @ syn_pb.bone.matrix_local.inverted()).to_quaternion()
    return delta @ syn_rest_dir


def aim_bone(mh_pb, target_dir, frame):
    """Point an MH bone along target_dir in world space, keyframe it."""
    mh_pb.rotation_mode = "QUATERNION"
    mh_rest_dir = (Vector(mh_pb.bone.tail_local) -
                   Vector(mh_pb.bone.head_local)).normalized()
    aim = mh_rest_dir.rotation_difference(target_dir)
    rest_rot = mh_pb.bone.matrix_local.to_quaternion()
    keep_loc = mh_pb.matrix.to_translation()
    mh_pb.matrix = (Matrix.Translation(keep_loc) @
                    (aim @ rest_rot).to_matrix().to_4x4())
    bpy.context.view_layer.update()
    mh_pb.keyframe_insert("rotation_quaternion", frame=frame)
    return aim


def drive_shoulder_girdle(driver, rig, frame):
    """Scapulohumeral rhythm: the shoulder girdle is not a hinge — past ~30°
    of arm elevation the clavicle and scapula rotate too (~1° of girdle per
    2° of arm). Without this the clavicle stays frozen while the humerus
    swings overhead and the deltoid/shoulder mesh collapses. Girdle bones are
    driven BEFORE the arm so the arm's world aim stays exact."""
    for side in (".L", ".R"):
        syn_pb = driver.pose.bones.get("upper_arm" + side)
        arm_pb = rig.pose.bones.get("upperarm01" + side)
        if syn_pb is None or arm_pb is None:
            continue
        target_dir = driver_target_dir(syn_pb)
        arm_rest_dir = (Vector(arm_pb.bone.tail_local) -
                        Vector(arm_pb.bone.head_local)).normalized()
        arm_aim = arm_rest_dir.rotation_difference(target_dir)

        elevation = math.degrees(arm_aim.angle)
        if elevation <= 30.0:
            follow = 0.0                      # setting phase: girdle stays put
        else:
            follow = min(1.0, (elevation - 30.0) / 120.0)

        identity = Quaternion()
        for bone_name, share in (("clavicle" + side, 0.22),
                                 ("shoulder01" + side, 0.40)):
            pb = rig.pose.bones.get(bone_name)
            if pb is None:
                continue
            pb.rotation_mode = "QUATERNION"
            partial = identity.slerp(arm_aim, share * follow)
            keep_loc = pb.matrix.to_translation()
            pb.matrix = (Matrix.Translation(keep_loc) @
                         partial.to_matrix().to_4x4() @
                         pb.bone.matrix_local.to_quaternion().to_matrix().to_4x4())
            bpy.context.view_layer.update()
            pb.keyframe_insert("rotation_quaternion", frame=frame)


def transfer_pose(driver, rig, root_offset, frame):
    """Aim each MakeHuman bone at its driver bone's posed world direction."""
    arm_entries = []
    for syn_name, mh_name in RETARGET:
        syn_pb = driver.pose.bones[syn_name]
        mh_pb = rig.pose.bones.get(mh_name)
        if mh_pb is None:
            continue
        if mh_name.startswith(("upperarm", "lowerarm", "wrist")):
            arm_entries.append((syn_pb, mh_pb))     # deferred: needs the girdle
            continue
        mh_pb.rotation_mode = "QUATERNION"

        if syn_name == "pelvis":
            # full transform: world rotation recentered on the MH root head,
            # so lying/leaning exercises (push-up, bridge) carry the legs too
            delta_q = (syn_pb.matrix @
                       syn_pb.bone.matrix_local.inverted()).to_quaternion()
            h = Vector(mh_pb.bone.head_local)
            mh_pb.matrix = (Matrix.Translation(root_offset + h) @
                            delta_q.to_matrix().to_4x4() @
                            Matrix.Translation(-h) @ mh_pb.bone.matrix_local)
            bpy.context.view_layer.update()
            mh_pb.keyframe_insert("location", frame=frame)
            mh_pb.keyframe_insert("rotation_quaternion", frame=frame)
            continue

        aim_bone(mh_pb, driver_target_dir(syn_pb), frame)

    drive_shoulder_girdle(driver, rig, frame)
    for syn_pb, mh_pb in arm_entries:
        aim_bone(mh_pb, driver_target_dir(syn_pb), frame)


def animate(driver, rig, spec, frame_end):
    for kf in spec["keyframes"]:
        frame = 1 + round(kf["t"] * (frame_end - 1))
        root_offset = pose_driver(driver, kf)
        transfer_pose(driver, rig, root_offset, frame)
    # ease every curve without overshoot — reps settle instead of bouncing
    action = rig.animation_data.action if rig.animation_data else None
    if action:
        for fcurve in action.fcurves:
            for kp in fcurve.keyframe_points:
                kp.interpolation = "BEZIER"
                kp.handle_left_type = kp.handle_right_type = "AUTO_CLAMPED"


# -------------------------------------------------------------------- render

def build_cyclorama():
    """Studio infinity backdrop: floor sweeping up into a back wall through a
    fillet, so there's no horizon seam behind the figure. Render-only —
    stripped before GLB export."""
    profile = [(-7.0, 0.0), (0.9, 0.0)]                  # floor
    radius, steps = 1.4, 10
    for i in range(1, steps + 1):                        # quarter-circle fillet
        a = (math.pi / 2) * (i / steps)
        profile.append((0.9 + radius * math.sin(a), radius * (1 - math.cos(a))))
    profile.append((0.9 + radius, radius + 5.0))         # wall

    mesh = bpy.data.meshes.new("Backdrop")
    verts, faces = [], []
    for x in (-7.0, 7.0):
        for y, z in profile:
            verts.append((x, y, z))
    n = len(profile)
    for i in range(n - 1):
        faces.append((i, i + 1, n + i + 1, n + i))
    mesh.from_pydata(verts, [], faces)
    mesh.update()
    backdrop = bpy.data.objects.new("Backdrop", mesh)
    bpy.context.scene.collection.objects.link(backdrop)
    backdrop.data.materials.append(
        make_material("Backdrop", (0.92, 0.93, 0.95, 1.0), roughness=0.9))
    for poly in backdrop.data.polygons:
        poly.use_smooth = True
    return backdrop


def area_light(name, energy, size, location, look_at=Vector((0, 0, 1.0))):
    data = bpy.data.lights.new(name, "AREA")
    data.energy = energy
    data.size = size
    data.shape = "SQUARE"
    obj = bpy.data.objects.new(name, data)
    obj.location = location
    direction = (look_at - Vector(location))
    obj.rotation_euler = direction.to_track_quat("-Z", "Y").to_euler()
    bpy.context.scene.collection.objects.link(obj)
    return obj


def frame_subject(cam, target, basemesh, frames, margin=1.12):
    """Fit the camera to the figure across every keyframe pose, so the shot
    is tight but nothing clips mid-rep and the camera never drifts."""
    lo = Vector((1e9, 1e9, 1e9))
    hi = Vector((-1e9, -1e9, -1e9))
    for f in frames:
        bpy.context.scene.frame_set(f)
        deps = bpy.context.evaluated_depsgraph_get()
        evaluated = basemesh.evaluated_get(deps)
        matrix = basemesh.matrix_world
        for v in evaluated.data.vertices:
            co = matrix @ v.co
            lo = Vector((min(lo.x, co.x), min(lo.y, co.y), min(lo.z, co.z)))
            hi = Vector((max(hi.x, co.x), max(hi.y, co.y), max(hi.z, co.z)))

    center = (lo + hi) / 2
    radius = (hi - lo).length / 2
    target.location = center
    view_dir = Vector((0.55, -0.80, 0.20)).normalized()   # keep the 3/4 angle
    distance = radius / math.tan(cam.data.angle / 2) * margin
    cam.location = center + view_dir * distance


def setup_render():
    scene = bpy.context.scene
    target = bpy.data.objects.new("CamTarget", None)
    scene.collection.objects.link(target)

    # 85mm = portrait lens, no wide-angle limb distortion; frame_subject
    # positions it once the pose is known
    cam_data = bpy.data.cameras.new("Cam")
    cam_data.lens = 85
    cam = bpy.data.objects.new("Cam", cam_data)
    scene.collection.objects.link(cam)
    cam.constraints.new("TRACK_TO").target = target
    scene.camera = cam

    # Softbox three-point rig (area lights wrap; sun lamps stamp hard edges).
    # Energies are exposure-solved, not eyeballed: irradiance E ≈ P/(4π·d²),
    # and a diffuse surface reads L = E·albedo/π. For AgX mid-grey (~0.2) at
    # albedo 0.6 from ~4 m, the key wants ≈450 W. Earlier rigs ran 900-1400 W
    # (~2-3 stops hot) which is what bleached the figure and turned the
    # muscle reds pink — blown channels desaturate.
    area_light("Key", 450, 2.5, (2.6, -3.0, 3.4))
    area_light("Fill", 90, 6.0, (-3.4, -2.2, 1.8))
    area_light("Rim", 250, 2.0, (-1.6, 3.2, 2.8))

    build_cyclorama()

    world = bpy.data.worlds.new("World")
    world.use_nodes = True
    bg = world.node_tree.nodes["Background"]
    bg.inputs["Color"].default_value = (0.70, 0.72, 0.75, 1.0)
    bg.inputs["Strength"].default_value = 0.12   # ambient only; lights do the work
    scene.world = world

    scene.render.engine = "CYCLES"
    scene.cycles.samples = 64
    scene.cycles.use_denoising = True            # few samples, clean output
    scene.cycles.max_bounces = 6
    scene.view_settings.view_transform = "AgX"   # filmic highlight rolloff
    scene.view_settings.look = "AgX - Punchy"    # saturation back after AgX
    scene.render.resolution_x = scene.render.resolution_y = 512
    return cam, target


def main():
    argv = sys.argv[sys.argv.index("--") + 1:]
    spec_path, out_dir = argv[0], argv[1]
    with open(spec_path) as f:
        spec = json.load(f)

    ensure_mpfb()
    for obj in list(bpy.data.objects):     # drop the default cube/camera/light
        bpy.data.objects.remove(obj, do_unlink=True)
    scene = bpy.context.scene
    scene.render.fps = spec.get("fps", 30)
    frame_end = round(spec.get("duration", 2.0) * scene.render.fps)
    scene.frame_start, scene.frame_end = 1, frame_end

    basemesh, rig = create_human()
    strip_helpers(basemesh)
    # no emission on the muscles — it fights the tonemapper and turns the
    # highlight pastel; saturated base colour reads far stronger
    materials = {
        "skin": make_material("Skin", SKIN_COLOR, subsurface=0.05),
        "primary": make_material("Primary", PRIMARY_COLOR, subsurface=0.05),
        "secondary": make_material("Secondary", SECONDARY_COLOR, subsurface=0.05),
    }
    primary, secondary = highlight_sets(spec)
    paint_muscles(basemesh, rig, materials, primary, secondary)

    bones, parents = full_skeleton()
    driver = build_driver(bones, parents)
    animate(driver, rig, spec, frame_end)
    bpy.data.objects.remove(driver, do_unlink=True)

    cam, target = setup_render()
    key_frames = sorted({1 + round(kf["t"] * (frame_end - 1))
                         for kf in spec["keyframes"]})
    still_frame = 1 + (frame_end - 1) // 2      # mid-rep = most telling pose

    # thumbnail: frame that one pose tightly
    frame_subject(cam, target, basemesh, [still_frame])
    scene.frame_set(still_frame)
    scene.render.filepath = f"{out_dir}/{spec['id']}.png"
    bpy.ops.render.render(write_still=True)

    # animation: frame the whole rep so the camera never drifts or clips
    frame_subject(cam, target, basemesh, key_frames)

    # small animation frames for GIF/MP4 (watch-sized); ffmpeg assembles in CI
    scene.render.resolution_x = scene.render.resolution_y = 240
    scene.cycles.samples = 12
    scene.frame_step = 2                     # 15 fps effective
    scene.render.filepath = f"{out_dir}/frames_{spec['id']}/"
    bpy.ops.render.render(animation=True)

    backdrop = bpy.data.objects.get("Backdrop")
    if backdrop:
        bpy.data.objects.remove(backdrop, do_unlink=True)
    bpy.ops.export_scene.gltf(filepath=f"{out_dir}/{spec['id']}.glb")
    print(f"OK {spec['id']}: {frame_end} frames -> {out_dir}")


main()
