"""Build a rigged, animated exercise figure and export GLB + thumbnail.

Runs headless inside Blender in CI (no GPU needed):

    blender -b -noaudio --python-exit-code 1 -P pipeline/build_exercise.py -- exercises/squat.json site/assets

v0.4: the figure is a real anatomical human generated by MPFB2 (MakeHuman
for Blender) — male, muscle 0.9 — rigged with the canonical MakeHuman
skeleton. Poses stay in the same exercise JSONs: a hidden synthetic
"driver" rig evaluates them, then each MakeHuman bone is aimed at the
driver bone's world direction (shortest arc), so the retarget is
independent of the two rigs' different rest poses (MPFB rests in A-pose).
Active muscle regions are painted onto the body via MakeHuman's own
skin-weight territories. Writes <id>.glb and <id>.png (mid-rep frame).
"""

import importlib
import json
import math
import os
import sys
import urllib.request
import zipfile

import bmesh
import bpy
from mathutils import Matrix, Quaternion, Vector

MPFB_URL = ("https://extensions.blender.org/download/"
            "sha256:b5cdc8b08147e0c6463e4faa01147491b13a0b062f73415363f029debd11c934/"
            "add-on-mpfb-v2.0.16.zip?repository=%2Fapi%2Fv1%2Fextensions%2F"
            "&blender_version_min=4.2.0")

# Driver skeleton (pose JSONs are authored against these rest directions).
# World coords, character faces -Y. name: (head, tail)
BONES = {
    "pelvis":      ((0.00, 0.0, 0.95), (0.00, 0.0, 1.06)),
    "spine":       ((0.00, 0.0, 1.06), (0.00, 0.0, 1.30)),
    "chest":       ((0.00, 0.0, 1.30), (0.00, 0.0, 1.50)),
    "neck":        ((0.00, 0.0, 1.50), (0.00, 0.0, 1.58)),
    "head":        ((0.00, 0.0, 1.58), (0.00, 0.0, 1.76)),
    "upper_arm.L": ((0.18, 0.0, 1.46), (0.42, 0.0, 1.46)),
    "forearm.L":   ((0.42, 0.0, 1.46), (0.66, 0.0, 1.46)),
    "hand.L":      ((0.66, 0.0, 1.46), (0.78, 0.0, 1.46)),
    "thigh.L":     ((0.10, 0.0, 0.95), (0.10, 0.0, 0.52)),
    "shin.L":      ((0.10, 0.0, 0.52), (0.10, 0.0, 0.09)),
    "foot.L":      ((0.10, 0.0, 0.09), (0.10, -0.18, 0.02)),
}

PARENTS = {
    "spine": "pelvis", "chest": "spine", "neck": "chest", "head": "neck",
    "upper_arm.L": "chest", "forearm.L": "upper_arm.L", "hand.L": "forearm.L",
    "thigh.L": "pelvis", "shin.L": "thigh.L", "foot.L": "shin.L",
}

# driver bone -> MakeHuman default-rig bone (aim transfer, parent-first order)
RETARGET = [
    ("pelvis", "root"),
    ("spine", "spine03"), ("chest", "spine01"),
    ("neck", "neck01"), ("head", "head"),
    ("thigh.L", "upperleg01.L"), ("thigh.L", "upperleg02.L"),
    ("shin.L", "lowerleg01.L"), ("shin.L", "lowerleg02.L"), ("foot.L", "foot.L"),
    ("thigh.R", "upperleg01.R"), ("thigh.R", "upperleg02.R"),
    ("shin.R", "lowerleg01.R"), ("shin.R", "lowerleg02.R"), ("foot.R", "foot.R"),
    ("upper_arm.L", "upperarm01.L"), ("upper_arm.L", "upperarm02.L"),
    ("forearm.L", "lowerarm01.L"), ("forearm.L", "lowerarm02.L"), ("hand.L", "wrist.L"),
    ("upper_arm.R", "upperarm01.R"), ("upper_arm.R", "upperarm02.R"),
    ("forearm.R", "lowerarm01.R"), ("forearm.R", "lowerarm02.R"), ("hand.R", "wrist.R"),
]

# exercise-metadata muscle names -> MakeHuman bones whose skin territory
# gets painted red/orange
MUSCLE_BONES = {
    "quads": ["upperleg01", "upperleg02"], "hamstrings": ["upperleg01", "upperleg02"],
    "glutes": ["pelvis"], "calves": ["lowerleg01", "lowerleg02"],
    "core": ["spine03", "spine02"], "abs": ["spine03", "spine02"],
    "lower back": ["spine04", "spine05"],
    "chest": ["breast"], "pecs": ["breast"],
    "lats": ["spine02", "spine01"], "back": ["spine02", "spine01"],
    "traps": ["neck01", "neck02", "neck03"],
    "shoulders": ["shoulder01", "clavicle"], "front delts": ["shoulder01", "clavicle"],
    "delts": ["shoulder01", "clavicle"],
    "biceps": ["upperarm01", "upperarm02"], "triceps": ["upperarm01", "upperarm02"],
    "forearms": ["lowerarm01", "lowerarm02"],
}

HELPER_GROUPS = ("HelperGeometry", "JointCubes", "eye.L", "eye.R")

SKIN_COLOR = (0.70, 0.72, 0.76, 1.0)
PRIMARY_COLOR = (0.80, 0.08, 0.10, 1.0)
SECONDARY_COLOR = (0.93, 0.50, 0.08, 1.0)


# ---------------------------------------------------------------- mpfb setup

def ensure_mpfb():
    version = f"{bpy.app.version[0]}.{bpy.app.version[1]}"
    ext_root = os.path.expanduser(f"~/.config/blender/{version}/extensions/user_default")
    dest = os.path.join(ext_root, "mpfb")
    if not os.path.isdir(dest):
        os.makedirs(ext_root, exist_ok=True)
        zpath = "/tmp/mpfb.zip"
        if not os.path.exists(zpath):
            req = urllib.request.Request(       # site 403s python's default UA
                MPFB_URL, headers={"User-Agent": "Mozilla/5.0 (X11; Linux x86_64)"})
            with urllib.request.urlopen(req) as resp, open(zpath, "wb") as f:
                f.write(resp.read())
        with zipfile.ZipFile(zpath) as z:
            names = z.namelist()
            if any(n.split("/")[0] == "blender_manifest.toml" for n in names):
                z.extractall(dest)
            else:
                z.extractall(ext_root)
                top = names[0].split("/")[0]
                if top != "mpfb":
                    os.rename(os.path.join(ext_root, top), dest)
    bpy.ops.preferences.addon_enable(module="bl_ext.user_default.mpfb")


def dynamic_import(absolute_package_str, key):
    """MPFB's own quirk: extensions land at unknown module paths."""
    for amod in list(sys.modules):
        if amod.endswith(absolute_package_str):
            return getattr(importlib.import_module(amod), key)
    raise ValueError(f"no module ending in {absolute_package_str}")


def create_human():
    HumanService = dynamic_import("mpfb.services.humanservice", "HumanService")
    HumanObjectProperties = dynamic_import("mpfb.entities.objectproperties",
                                           "HumanObjectProperties")
    TargetService = dynamic_import("mpfb.services.targetservice", "TargetService")
    basemesh = HumanService.create_human()
    for prop, value in (("gender", 1.0), ("muscle", 1.0), ("weight", 0.55)):
        HumanObjectProperties.set_value(prop, value, entity_reference=basemesh)
    TargetService.reapply_macro_details(basemesh)
    rig = HumanService.add_builtin_rig(basemesh, "default")
    return basemesh, rig


def strip_helpers(basemesh):
    """MakeHuman's base mesh ships clothes-fitting scaffolding — remove it."""
    kill = {g.index for g in basemesh.vertex_groups if g.name in HELPER_GROUPS}
    doomed = [v.index for v in basemesh.data.vertices
              if any(ge.group in kill for ge in v.groups)]
    bm = bmesh.new()
    bm.from_mesh(basemesh.data)
    bm.verts.ensure_lookup_table()
    bmesh.ops.delete(bm, geom=[bm.verts[i] for i in doomed], context="VERTS")
    bm.to_mesh(basemesh.data)
    bm.free()


# ------------------------------------------------------------------ painting

def make_material(name, color, emission=0.0, roughness=0.55, subsurface=0.0):
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes["Principled BSDF"]
    bsdf.inputs["Base Color"].default_value = color
    bsdf.inputs["Roughness"].default_value = roughness
    if emission:
        bsdf.inputs["Emission Color"].default_value = color
        bsdf.inputs["Emission Strength"].default_value = emission
    if subsurface and "Subsurface Weight" in bsdf.inputs:
        bsdf.inputs["Subsurface Weight"].default_value = subsurface
    return mat


def highlight_sets(spec):
    """Muscle metadata -> sets of MakeHuman bone-territory prefixes."""
    primary, secondary = set(), set()
    for group, out in ((spec.get("primary", []), primary),
                       (spec.get("secondary", []), secondary)):
        for muscle in group:
            out.update(MUSCLE_BONES.get(muscle.lower(), []))
    return primary, secondary - primary


def paint_muscles(basemesh, materials, primary, secondary, bone_names):
    """Paint faces whose dominant skin-weight territory belongs to an active
    muscle. Only real rig-bone groups count — MakeHuman's meta groups
    (body/Left/Right/Mid) carry full weights everywhere and must be
    ignored. The membership field is Laplacian-smoothed so borders curve."""
    mesh = basemesh.data
    name_by_index = {g.index: g.name for g in basemesh.vertex_groups}

    def in_set(names_set, group_name):
        base = group_name.split(".")[0]
        return base in names_set

    score_p, score_s = [], []
    for v in mesh.vertices:
        best, best_w = None, 0.0
        for ge in v.groups:
            name = name_by_index.get(ge.group)
            if name in bone_names and ge.weight > best_w:
                best, best_w = name, ge.weight
        score_p.append(1.0 if best and in_set(primary, best) else 0.0)
        score_s.append(1.0 if best and in_set(secondary, best) else 0.0)

    neighbors = [[] for _ in mesh.vertices]
    for edge in mesh.edges:
        a, b = edge.vertices
        neighbors[a].append(b)
        neighbors[b].append(a)
    for _ in range(4):
        for score in (score_p, score_s):
            snapshot = score[:]
            for i, ns in enumerate(neighbors):
                if ns:
                    score[i] = 0.5 * snapshot[i] + \
                        0.5 * sum(snapshot[j] for j in ns) / len(ns)

    mesh.materials.clear()
    mesh.materials.append(materials["skin"])
    mesh.materials.append(materials["primary"])
    mesh.materials.append(materials["secondary"])
    for poly in mesh.polygons:
        p = sum(score_p[i] for i in poly.vertices) / len(poly.vertices)
        s = sum(score_s[i] for i in poly.vertices) / len(poly.vertices)
        if p > 0.45 and p >= s:
            poly.material_index = 1
        elif s > 0.45:
            poly.material_index = 2
        else:
            poly.material_index = 0


# ---------------------------------------------------------------- retargeting

def mirror_name(name):
    return name[:-2] + ".R" if name.endswith(".L") else name


def full_skeleton():
    bones, parents = {}, {}
    for name, (head, tail) in BONES.items():
        bones[name] = (Vector(head), Vector(tail))
        if name.endswith(".L"):
            r = mirror_name(name)
            bones[r] = (Vector((-head[0], head[1], head[2])),
                        Vector((-tail[0], tail[1], tail[2])))
    for child, parent in PARENTS.items():
        parents[child] = parent
        if child.endswith(".L"):
            parents[mirror_name(child)] = mirror_name(parent)
    return bones, parents


def build_driver(bones, parents):
    arm_data = bpy.data.armatures.new("Driver")
    arm_obj = bpy.data.objects.new("Driver", arm_data)
    bpy.context.scene.collection.objects.link(arm_obj)
    bpy.context.view_layer.objects.active = arm_obj
    bpy.ops.object.mode_set(mode="EDIT")
    for name, (head, tail) in bones.items():
        eb = arm_data.edit_bones.new(name)
        eb.head, eb.tail, eb.roll = head, tail, 0.0
    for child, parent in parents.items():
        arm_data.edit_bones[child].parent = arm_data.edit_bones[parent]
    bpy.ops.object.mode_set(mode="OBJECT")
    return arm_obj


def pose_targets(kf_bones):
    """Expand 'thigh.*' wildcards into mirrored .L/.R transforms."""
    for name, xf in kf_bones.items():
        rot = xf.get("rot", [0, 0, 0])
        loc = xf.get("loc")
        if name.endswith(".*"):
            base = name[:-2]
            yield base + ".L", rot, loc
            mrot = [rot[0], -rot[1], -rot[2]]
            mloc = [-loc[0], loc[1], loc[2]] if loc else None
            yield base + ".R", mrot, mloc
        else:
            yield name, rot, loc


def pose_driver(driver, kf):
    root_offset = Vector((0, 0, 0))
    for bone_name, rot, loc in pose_targets(kf.get("bones", {})):
        pb = driver.pose.bones[bone_name]
        pb.rotation_mode = "XYZ"
        pb.rotation_euler = [math.radians(a) for a in rot]
        if loc is not None and bone_name == "pelvis":
            root_offset = Vector(loc)
    bpy.context.view_layer.update()
    return root_offset


def driver_target_dir(syn_pb):
    """World direction the driver bone points in its current pose."""
    syn_rest_dir = (Vector(syn_pb.bone.tail_local) -
                    Vector(syn_pb.bone.head_local)).normalized()
    delta = (syn_pb.matrix @ syn_pb.bone.matrix_local.inverted()).to_quaternion()
    return delta @ syn_rest_dir


def aim_bone(mh_pb, target_dir, frame):
    """Point an MH bone along target_dir in world space, keyframe it."""
    mh_pb.rotation_mode = "QUATERNION"
    mh_rest_dir = (Vector(mh_pb.bone.tail_local) -
                   Vector(mh_pb.bone.head_local)).normalized()
    aim = mh_rest_dir.rotation_difference(target_dir)
    rest_rot = mh_pb.bone.matrix_local.to_quaternion()
    keep_loc = mh_pb.matrix.to_translation()
    mh_pb.matrix = (Matrix.Translation(keep_loc) @
                    (aim @ rest_rot).to_matrix().to_4x4())
    bpy.context.view_layer.update()
    mh_pb.keyframe_insert("rotation_quaternion", frame=frame)
    return aim


def drive_shoulder_girdle(driver, rig, frame):
    """Scapulohumeral rhythm: the shoulder girdle is not a hinge — past ~30°
    of arm elevation the clavicle and scapula rotate too (~1° of girdle per
    2° of arm). Without this the clavicle stays frozen while the humerus
    swings overhead and the deltoid/shoulder mesh collapses. Girdle bones are
    driven BEFORE the arm so the arm's world aim stays exact."""
    for side in (".L", ".R"):
        syn_pb = driver.pose.bones.get("upper_arm" + side)
        arm_pb = rig.pose.bones.get("upperarm01" + side)
        if syn_pb is None or arm_pb is None:
            continue
        target_dir = driver_target_dir(syn_pb)
        arm_rest_dir = (Vector(arm_pb.bone.tail_local) -
                        Vector(arm_pb.bone.head_local)).normalized()
        arm_aim = arm_rest_dir.rotation_difference(target_dir)

        elevation = math.degrees(arm_aim.angle)
        if elevation <= 30.0:
            follow = 0.0                      # setting phase: girdle stays put
        else:
            follow = min(1.0, (elevation - 30.0) / 120.0)

        identity = Quaternion()
        for bone_name, share in (("clavicle" + side, 0.22),
                                 ("shoulder01" + side, 0.40)):
            pb = rig.pose.bones.get(bone_name)
            if pb is None:
                continue
            pb.rotation_mode = "QUATERNION"
            partial = identity.slerp(arm_aim, share * follow)
            keep_loc = pb.matrix.to_translation()
            pb.matrix = (Matrix.Translation(keep_loc) @
                         partial.to_matrix().to_4x4() @
                         pb.bone.matrix_local.to_quaternion().to_matrix().to_4x4())
            bpy.context.view_layer.update()
            pb.keyframe_insert("rotation_quaternion", frame=frame)


def transfer_pose(driver, rig, root_offset, frame):
    """Aim each MakeHuman bone at its driver bone's posed world direction."""
    arm_entries = []
    for syn_name, mh_name in RETARGET:
        syn_pb = driver.pose.bones[syn_name]
        mh_pb = rig.pose.bones.get(mh_name)
        if mh_pb is None:
            continue
        if mh_name.startswith(("upperarm", "lowerarm", "wrist")):
            arm_entries.append((syn_pb, mh_pb))     # deferred: needs the girdle
            continue
        mh_pb.rotation_mode = "QUATERNION"

        if syn_name == "pelvis":
            # full transform: world rotation recentered on the MH root head,
            # so lying/leaning exercises (push-up, bridge) carry the legs too
            delta_q = (syn_pb.matrix @
                       syn_pb.bone.matrix_local.inverted()).to_quaternion()
            h = Vector(mh_pb.bone.head_local)
            mh_pb.matrix = (Matrix.Translation(root_offset + h) @
                            delta_q.to_matrix().to_4x4() @
                            Matrix.Translation(-h) @ mh_pb.bone.matrix_local)
            bpy.context.view_layer.update()
            mh_pb.keyframe_insert("location", frame=frame)
            mh_pb.keyframe_insert("rotation_quaternion", frame=frame)
            continue

        aim_bone(mh_pb, driver_target_dir(syn_pb), frame)

    drive_shoulder_girdle(driver, rig, frame)
    for syn_pb, mh_pb in arm_entries:
        aim_bone(mh_pb, driver_target_dir(syn_pb), frame)


def animate(driver, rig, spec, frame_end):
    for kf in spec["keyframes"]:
        frame = 1 + round(kf["t"] * (frame_end - 1))
        root_offset = pose_driver(driver, kf)
        transfer_pose(driver, rig, root_offset, frame)
    # ease every curve without overshoot — reps settle instead of bouncing
    action = rig.animation_data.action if rig.animation_data else None
    if action:
        for fcurve in action.fcurves:
            for kp in fcurve.keyframe_points:
                kp.interpolation = "BEZIER"
                kp.handle_left_type = kp.handle_right_type = "AUTO_CLAMPED"


# -------------------------------------------------------------------- render

def setup_render(frame_end):
    scene = bpy.context.scene
    target = bpy.data.objects.new("CamTarget", None)
    target.location = (0, 0, 0.85)
    scene.collection.objects.link(target)

    cam_data = bpy.data.cameras.new("Cam")
    cam = bpy.data.objects.new("Cam", cam_data)
    cam.location = (1.7, -2.6, 1.35)
    scene.collection.objects.link(cam)
    cam.constraints.new("TRACK_TO").target = target
    scene.camera = cam

    sun_data = bpy.data.lights.new("Sun", "SUN")
    sun_data.energy = 4.5
    sun_data.angle = 0.18            # soft-edged key shadow
    sun = bpy.data.objects.new("Sun", sun_data)
    sun.rotation_euler = (math.radians(50), math.radians(-15), math.radians(30))
    scene.collection.objects.link(sun)

    fill_data = bpy.data.lights.new("Fill", "SUN")
    fill_data.energy = 1.2
    fill = bpy.data.objects.new("Fill", fill_data)
    fill.rotation_euler = (math.radians(60), math.radians(20), math.radians(-140))
    scene.collection.objects.link(fill)

    rim_data = bpy.data.lights.new("Rim", "SUN")
    rim_data.energy = 2.0
    rim = bpy.data.objects.new("Rim", rim_data)
    rim.rotation_euler = (math.radians(-65), math.radians(-10), math.radians(160))
    scene.collection.objects.link(rim)

    # ground plane anchors the figure with a soft contact shadow (render
    # only — removed before GLB export, the viewer has its own grid floor)
    bpy.ops.mesh.primitive_plane_add(size=14, location=(0, 0, 0))
    ground = bpy.context.object
    ground.name = "Ground"
    ground.data.materials.append(
        make_material("Ground", (0.90, 0.91, 0.93, 1.0), roughness=0.95))

    world = bpy.data.worlds.new("World")
    world.use_nodes = True
    bg = world.node_tree.nodes["Background"]
    bg.inputs["Color"].default_value = (0.94, 0.95, 0.96, 1.0)
    bg.inputs["Strength"].default_value = 1.0
    scene.world = world

    scene.render.engine = "CYCLES"
    scene.cycles.samples = 48
    scene.render.resolution_x = scene.render.resolution_y = 512
    scene.frame_set(1 + (frame_end - 1) // 2)  # mid-rep = most telling pose


def main():
    argv = sys.argv[sys.argv.index("--") + 1:]
    spec_path, out_dir = argv[0], argv[1]
    with open(spec_path) as f:
        spec = json.load(f)

    ensure_mpfb()
    for obj in list(bpy.data.objects):     # drop the default cube/camera/light
        bpy.data.objects.remove(obj, do_unlink=True)
    scene = bpy.context.scene
    scene.render.fps = spec.get("fps", 30)
    frame_end = round(spec.get("duration", 2.0) * scene.render.fps)
    scene.frame_start, scene.frame_end = 1, frame_end

    basemesh, rig = create_human()
    strip_helpers(basemesh)
    materials = {
        "skin": make_material("Skin", SKIN_COLOR, subsurface=0.06),
        "primary": make_material("Primary", PRIMARY_COLOR, emission=0.3,
                                 subsurface=0.06),
        "secondary": make_material("Secondary", SECONDARY_COLOR, emission=0.15,
                                   subsurface=0.06),
    }
    primary, secondary = highlight_sets(spec)
    paint_muscles(basemesh, materials, primary, secondary,
                  {b.name for b in rig.data.bones})

    bones, parents = full_skeleton()
    driver = build_driver(bones, parents)
    animate(driver, rig, spec, frame_end)
    bpy.data.objects.remove(driver, do_unlink=True)

    setup_render(frame_end)
    scene.render.filepath = f"{out_dir}/{spec['id']}.png"
    bpy.ops.render.render(write_still=True)

    # small animation frames for GIF/MP4 (watch-sized); ffmpeg assembles in CI
    scene.render.resolution_x = scene.render.resolution_y = 240
    scene.cycles.samples = 12
    scene.frame_step = 2                     # 15 fps effective
    scene.render.filepath = f"{out_dir}/frames_{spec['id']}/"
    bpy.ops.render.render(animation=True)

    ground = bpy.data.objects.get("Ground")
    if ground:
        bpy.data.objects.remove(ground, do_unlink=True)
    bpy.ops.export_scene.gltf(filepath=f"{out_dir}/{spec['id']}.glb")
    print(f"OK {spec['id']}: {frame_end} frames -> {out_dir}")


main()
